// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: utxos.sql

package sqlcsqlite

import (
	"context"
	"database/sql"
	"time"
)

const Balance = `-- name: Balance :one
SELECT cast(coalesce(sum(u.amount), 0) AS INTEGER) AS balance
FROM utxos AS u
INNER JOIN transactions AS t
    ON u.wallet_id = t.wallet_id AND u.tx_id = t.id
INNER JOIN addresses AS a ON u.address_id = a.id
INNER JOIN accounts AS acc ON a.account_id = acc.id
INNER JOIN key_scopes AS ks ON acc.scope_id = ks.id
LEFT JOIN wallet_sync_states AS s ON u.wallet_id = s.wallet_id
WHERE
    u.wallet_id = ?1
    AND ks.wallet_id = ?1
    AND u.spent_by_tx_id IS NULL
    AND t.status IN ('pending', 'published')
    AND (
        ?2 IS NULL
        OR acc.account_number = ?2
    )
    AND (
        ?3 IS NULL
        OR (
            CASE
                WHEN t.block_height IS NULL THEN 0
                WHEN s.synced_height IS NULL THEN 0
                WHEN t.block_height > s.synced_height THEN 0
                ELSE s.synced_height - t.block_height + 1
            END
        ) >= ?3
    )
    AND (
        ?4 IS NULL
        OR (
            CASE
                WHEN t.block_height IS NULL THEN 0
                WHEN s.synced_height IS NULL THEN 0
                WHEN t.block_height > s.synced_height THEN 0
                ELSE s.synced_height - t.block_height + 1
            END
        ) <= ?4
    )
    AND (
        ?5 = FALSE
        OR NOT EXISTS (
            SELECT 1
            FROM utxo_leases AS l
            WHERE
                l.wallet_id = u.wallet_id
                AND l.utxo_id = u.id
                AND l.expires_at > current_timestamp
        )
    )
    AND (
        ?6 IS NULL
        OR NOT t.is_coinbase
        OR (
            CASE
                WHEN t.block_height IS NULL THEN 0
                WHEN s.synced_height IS NULL THEN 0
                WHEN t.block_height > s.synced_height THEN 0
                ELSE s.synced_height - t.block_height + 1
            END
        ) >= ?6
    )
`

type BalanceParams struct {
	WalletID         int64
	AccountNumber    interface{}
	MinConfirms      interface{}
	MaxConfirms      interface{}
	ExcludeLeased    interface{}
	CoinbaseMaturity interface{}
}

// Returns the total value represented by the wallet's current unspent UTXO set.
//
// How:
//   - Starts from wallet-scoped unspent outputs and rejoins transactions plus
//     addresses -> accounts -> key_scopes so ownership validation and optional
//     account filtering stay in one read.
//   - Applies optional confirmation-range and coinbase-maturity policy directly
//     inside the aggregate query so callers can request factual or policy-shaped
//     balance reads through one public method.
//   - Leaves lease exclusion optional so callers can request either the raw live
//     balance or a stricter spendable view from the same public interface.
//
// Performance:
//   - Executes as one aggregate over wallet-scoped live outputs, with an
//     anti-join against utxo_leases only when requested.
func (q *Queries) Balance(ctx context.Context, arg BalanceParams) (int64, error) {
	row := q.queryRow(ctx, q.balanceStmt, Balance,
		arg.WalletID,
		arg.AccountNumber,
		arg.MinConfirms,
		arg.MaxConfirms,
		arg.ExcludeLeased,
		arg.CoinbaseMaturity,
	)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const ClearUtxosSpentByTxID = `-- name: ClearUtxosSpentByTxID :execrows
UPDATE utxos
SET
    spent_by_tx_id = NULL,
    spent_input_index = NULL
WHERE wallet_id = ?1 AND spent_by_tx_id = ?2
`

type ClearUtxosSpentByTxIDParams struct {
	WalletID    int64
	SpentByTxID sql.NullInt64
}

// Clears spent_by pointers for all UTXOs spent by the provided transaction ID.
//
// How:
//   - Resets both spent columns together so the logical spend pointer remains
//     internally consistent.
//
// Performance:
// - Uses the `(wallet_id, spent_by_tx_id)` index to find affected rows.
func (q *Queries) ClearUtxosSpentByTxID(ctx context.Context, arg ClearUtxosSpentByTxIDParams) (int64, error) {
	result, err := q.exec(ctx, q.clearUtxosSpentByTxIDStmt, ClearUtxosSpentByTxID, arg.WalletID, arg.SpentByTxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DeleteUtxosByTxID = `-- name: DeleteUtxosByTxID :execrows
DELETE FROM utxos
WHERE wallet_id = ?1 AND tx_id = ?2
`

type DeleteUtxosByTxIDParams struct {
	WalletID int64
	TxID     int64
}

// Deletes all UTXO rows created by the provided transaction ID.
//
// How:
//   - Removes outputs by the parent transaction's internal ID after callers have
//     already decided the transaction row itself may be deleted.
//
// Performance:
//   - Uses the `(wallet_id, tx_id)` index to keep the delete bounded to one
//     transaction's outputs.
func (q *Queries) DeleteUtxosByTxID(ctx context.Context, arg DeleteUtxosByTxIDParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteUtxosByTxIDStmt, DeleteUtxosByTxID, arg.WalletID, arg.TxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const GetUtxoByOutpoint = `-- name: GetUtxoByOutpoint :one
SELECT
    t.tx_hash,
    u.output_index,
    u.amount,
    a.script_pub_key,
    t.received_time,
    t.is_coinbase,
    t.block_height
FROM utxos AS u
INNER JOIN transactions AS t
    ON u.wallet_id = t.wallet_id AND u.tx_id = t.id
INNER JOIN addresses AS a ON u.address_id = a.id
INNER JOIN accounts AS acc ON a.account_id = acc.id
INNER JOIN key_scopes AS ks ON acc.scope_id = ks.id
WHERE
    u.wallet_id = ?1
    AND ks.wallet_id = ?1
    AND t.tx_hash = ?2
    AND u.output_index = ?3
    AND u.spent_by_tx_id IS NULL
    AND t.status IN ('pending', 'published')
`

type GetUtxoByOutpointParams struct {
	WalletID    int64
	TxHash      []byte
	OutputIndex int64
}

type GetUtxoByOutpointRow struct {
	TxHash       []byte
	OutputIndex  int64
	Amount       int64
	ScriptPubKey []byte
	ReceivedTime time.Time
	IsCoinbase   bool
	BlockHeight  sql.NullInt64
}

// Retrieves a single unspent UTXO by its outpoint.
//
// How:
//   - Joins utxos -> transactions on `(wallet_id, tx_id)` to resolve the outpoint
//     from tx hash plus output index.
//   - Joins addresses -> accounts -> key_scopes so the read path reasserts that
//     the credited address belongs to the requested wallet.
//   - Returns leased and unleased outputs alike because leasing affects coin
//     selection, not whether the UTXO exists.
//   - Treats outputs from both live unconfirmed parent states (`pending` and
//     `published`) as part of the wallet's current UTXO set.
//
// Performance:
//   - The wallet-scoped tx hash lookup and unique outpoint constraint keep the
//     join fanout to at most one candidate output.
func (q *Queries) GetUtxoByOutpoint(ctx context.Context, arg GetUtxoByOutpointParams) (GetUtxoByOutpointRow, error) {
	row := q.queryRow(ctx, q.getUtxoByOutpointStmt, GetUtxoByOutpoint, arg.WalletID, arg.TxHash, arg.OutputIndex)
	var i GetUtxoByOutpointRow
	err := row.Scan(
		&i.TxHash,
		&i.OutputIndex,
		&i.Amount,
		&i.ScriptPubKey,
		&i.ReceivedTime,
		&i.IsCoinbase,
		&i.BlockHeight,
	)
	return i, err
}

const GetUtxoIDByOutpoint = `-- name: GetUtxoIDByOutpoint :one
SELECT u.id
FROM utxos AS u
INNER JOIN transactions AS t
    ON u.wallet_id = t.wallet_id AND u.tx_id = t.id
INNER JOIN addresses AS a ON u.address_id = a.id
INNER JOIN accounts AS acc ON a.account_id = acc.id
INNER JOIN key_scopes AS ks ON acc.scope_id = ks.id
WHERE
    u.wallet_id = ?1
    AND ks.wallet_id = ?1
    AND t.tx_hash = ?2
    AND u.output_index = ?3
    AND u.spent_by_tx_id IS NULL
    AND t.status IN ('pending', 'published')
`

type GetUtxoIDByOutpointParams struct {
	WalletID    int64
	TxHash      []byte
	OutputIndex int64
}

// Retrieves the database ID for a current UTXO by its outpoint.
//
// How:
//   - Joins transactions on `(wallet_id, id)` so callers can address a UTXO by
//     network outpoint (`tx_hash`, `output_index`) instead of the internal row ID.
//   - Restricts the result to unspent outputs whose parent transaction is still
//     in a live state (`pending` or `published`).
//   - Rejoins addresses -> accounts -> key_scopes so helper lookups do not return
//     rows whose credited address does not actually belong to the wallet.
//   - Lease acquisition does not rely on this helper; it revalidates outpoint
//     liveness inside its own write statement to avoid stale-ID races.
//
// Performance:
//   - Uses the wallet-scoped transaction hash lookup first, then narrows to the
//     unique `(wallet_id, tx_id, output_index)` outpoint.
func (q *Queries) GetUtxoIDByOutpoint(ctx context.Context, arg GetUtxoIDByOutpointParams) (int64, error) {
	row := q.queryRow(ctx, q.getUtxoIDByOutpointStmt, GetUtxoIDByOutpoint, arg.WalletID, arg.TxHash, arg.OutputIndex)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const GetUtxoSpenderByOutpoint = `-- name: GetUtxoSpenderByOutpoint :one
SELECT u.spent_by_tx_id
FROM utxos AS u
INNER JOIN transactions AS t
    ON u.wallet_id = t.wallet_id AND u.tx_id = t.id
INNER JOIN addresses AS a ON u.address_id = a.id
INNER JOIN accounts AS acc ON a.account_id = acc.id
INNER JOIN key_scopes AS ks ON acc.scope_id = ks.id
WHERE
    u.wallet_id = ?1
    AND ks.wallet_id = ?1
    AND t.tx_hash = ?2
    AND u.output_index = ?3
    AND t.status IN ('pending', 'published')
`

type GetUtxoSpenderByOutpointParams struct {
	WalletID    int64
	TxHash      []byte
	OutputIndex int64
}

// Retrieves the current spender for a wallet-owned outpoint, if any.
//
// How:
//   - Resolves the outpoint through transactions so callers can address a UTXO by
//     tx hash plus output index instead of the internal row ID.
//   - Rejoins addresses -> accounts -> key_scopes so the lookup only reports
//     outputs that still belong to the requested wallet.
//   - Keeps the parent transaction in a live state (`pending` or `published`) so
//     callers only verify claims on outputs that remain part of the live wallet
//     graph.
//
// Performance:
//   - Uses the wallet-scoped tx hash lookup and unique outpoint constraint to
//     bound the read to at most one credited output.
func (q *Queries) GetUtxoSpenderByOutpoint(ctx context.Context, arg GetUtxoSpenderByOutpointParams) (sql.NullInt64, error) {
	row := q.queryRow(ctx, q.getUtxoSpenderByOutpointStmt, GetUtxoSpenderByOutpoint, arg.WalletID, arg.TxHash, arg.OutputIndex)
	var spent_by_tx_id sql.NullInt64
	err := row.Scan(&spent_by_tx_id)
	return spent_by_tx_id, err
}

const InsertUtxo = `-- name: InsertUtxo :one
INSERT INTO utxos (
    wallet_id,
    tx_id,
    output_index,
    amount,
    address_id
) SELECT
    ?1 AS wallet_id,
    ?2 AS tx_id,
    ?3 AS output_index,
    ?4 AS amount,
    a.id AS address_id
FROM addresses AS a
INNER JOIN accounts AS acc ON a.account_id = acc.id
INNER JOIN key_scopes AS ks ON acc.scope_id = ks.id
WHERE
    a.id = ?5
    AND ks.wallet_id = ?1
RETURNING id
`

type InsertUtxoParams struct {
	WalletID    int64
	TxID        int64
	OutputIndex int64
	Amount      int64
	AddressID   int64
}

// Inserts a new UTXO row and returns its database ID.
//
// How:
//   - Writes only the utxos table using already-resolved transaction and address
//     IDs.
//   - Rejoins addresses -> accounts -> key_scopes so the insert only succeeds if
//     the provided address ID belongs to the same wallet.
//
// Performance:
//   - Single-row insert. The main cost is the wallet-ownership validation join
//     plus FK and uniqueness checks.
func (q *Queries) InsertUtxo(ctx context.Context, arg InsertUtxoParams) (int64, error) {
	row := q.queryRow(ctx, q.insertUtxoStmt, InsertUtxo,
		arg.WalletID,
		arg.TxID,
		arg.OutputIndex,
		arg.Amount,
		arg.AddressID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ListSpendingTxIDsByParentTxID = `-- name: ListSpendingTxIDsByParentTxID :many
SELECT DISTINCT spent_by_tx_id
FROM utxos
WHERE
    wallet_id = ?1
    AND tx_id = ?2
    AND spent_by_tx_id IS NOT NULL
ORDER BY spent_by_tx_id
`

type ListSpendingTxIDsByParentTxIDParams struct {
	WalletID int64
	TxID     int64
}

// Lists direct child transaction IDs for one parent transaction ID.
//
// How:
//   - Reads the spend edges already materialized on utxos through
//     `(tx_id, spent_by_tx_id)`.
//   - Returns only direct children; callers that need full descendant walks should
//     traverse this query iteratively in application code.
//
// Performance:
//   - Uses the `(wallet_id, tx_id)` and `(wallet_id, spent_by_tx_id)` indexes to
//     keep the walk bounded to one wallet-scoped parent.
func (q *Queries) ListSpendingTxIDsByParentTxID(ctx context.Context, arg ListSpendingTxIDsByParentTxIDParams) ([]sql.NullInt64, error) {
	rows, err := q.query(ctx, q.listSpendingTxIDsByParentTxIDStmt, ListSpendingTxIDsByParentTxID, arg.WalletID, arg.TxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt64
	for rows.Next() {
		var spent_by_tx_id sql.NullInt64
		if err := rows.Scan(&spent_by_tx_id); err != nil {
			return nil, err
		}
		items = append(items, spent_by_tx_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUtxos = `-- name: ListUtxos :many
SELECT
    t.tx_hash,
    u.output_index,
    u.amount,
    a.script_pub_key,
    t.received_time,
    t.is_coinbase,
    t.block_height
FROM utxos AS u
INNER JOIN transactions AS t
    ON u.wallet_id = t.wallet_id AND u.tx_id = t.id
INNER JOIN addresses AS a ON u.address_id = a.id
INNER JOIN accounts AS acc ON a.account_id = acc.id
INNER JOIN key_scopes AS ks ON acc.scope_id = ks.id
LEFT JOIN wallet_sync_states AS s ON u.wallet_id = s.wallet_id
WHERE
    u.wallet_id = ?1
    AND ks.wallet_id = ?1
    AND u.spent_by_tx_id IS NULL
    AND t.status IN ('pending', 'published')
    AND (
        ?2 IS NULL
        OR acc.account_number = ?2
    )
    AND (
        CASE
            WHEN t.block_height IS NULL THEN 0
            WHEN s.synced_height IS NULL THEN 0
            WHEN t.block_height > s.synced_height THEN 0
            ELSE s.synced_height - t.block_height + 1
        END
    ) >= ?3
    AND (
        CASE
            WHEN t.block_height IS NULL THEN 0
            WHEN s.synced_height IS NULL THEN 0
            WHEN t.block_height > s.synced_height THEN 0
            ELSE s.synced_height - t.block_height + 1
        END
    ) <= ?4
ORDER BY u.amount, t.tx_hash, u.output_index
`

type ListUtxosParams struct {
	WalletID      int64
	AccountNumber interface{}
	MinConfirms   sql.NullInt64
	MaxConfirms   sql.NullInt64
}

type ListUtxosRow struct {
	TxHash       []byte
	OutputIndex  int64
	Amount       int64
	ScriptPubKey []byte
	ReceivedTime time.Time
	IsCoinbase   bool
	BlockHeight  sql.NullInt64
}

// Lists unspent UTXOs that match the provided filters.
//
// How:
//   - Starts from utxos and joins transactions for tx metadata plus
//     wallet_sync_states for confirmation math.
//   - Rejoins addresses -> accounts -> key_scopes so account filtering and wallet
//     ownership checks happen in the same read.
//   - Returns leased outputs too because the API models leases separately from
//     UTXO existence.
//   - Includes outputs whose parent transaction is still in a live unconfirmed
//     state (`pending` or `published`).
//   - Does not enforce coinbase maturity; callers that need a strictly spendable
//     set must apply chain-parameter maturity rules on top.
//
// Performance:
//   - Restricts first by wallet, spend state, and transaction status.
//   - Uses the address/account/scope joins to keep ownership validation and
//     account filtering in one pass.
func (q *Queries) ListUtxos(ctx context.Context, arg ListUtxosParams) ([]ListUtxosRow, error) {
	rows, err := q.query(ctx, q.listUtxosStmt, ListUtxos,
		arg.WalletID,
		arg.AccountNumber,
		arg.MinConfirms,
		arg.MaxConfirms,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUtxosRow
	for rows.Next() {
		var i ListUtxosRow
		if err := rows.Scan(
			&i.TxHash,
			&i.OutputIndex,
			&i.Amount,
			&i.ScriptPubKey,
			&i.ReceivedTime,
			&i.IsCoinbase,
			&i.BlockHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkUtxoSpent = `-- name: MarkUtxoSpent :execrows
UPDATE utxos
SET
    spent_by_tx_id = ?4,
    spent_input_index = ?5
WHERE
    utxos.wallet_id = ?1
    AND utxos.tx_id = (
        SELECT t.id
        FROM transactions AS t
        WHERE t.wallet_id = ?1 AND t.tx_hash = ?2
    )
    AND utxos.output_index = ?3
    AND (
        (utxos.spent_by_tx_id IS NULL AND utxos.spent_input_index IS NULL)
        OR (utxos.spent_by_tx_id = ?4 AND utxos.spent_input_index = ?5)
    )
`

type MarkUtxoSpentParams struct {
	WalletID        int64
	TxHash          []byte
	OutputIndex     int64
	SpentByTxID     sql.NullInt64
	SpentInputIndex sql.NullInt64
}

// Marks a wallet-owned UTXO as spent by a transaction.
//
// How:
//   - Resolves the created-by transaction row from `(wallet_id, tx_hash)` inside
//     the statement so callers can update by network outpoint.
//   - Only changes rows that are currently unspent or already point at the same
//     `(spent_by_tx_id, spent_input_index)` pair, which keeps retries idempotent
//     without allowing a caller to silently rewrite which input spent the UTXO.
//
// Performance:
//   - Targets one outpoint in one wallet; the subquery uses the unique
//     wallet-scoped tx hash lookup.
func (q *Queries) MarkUtxoSpent(ctx context.Context, arg MarkUtxoSpentParams) (int64, error) {
	result, err := q.exec(ctx, q.markUtxoSpentStmt, MarkUtxoSpent,
		arg.WalletID,
		arg.TxHash,
		arg.OutputIndex,
		arg.SpentByTxID,
		arg.SpentInputIndex,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
