// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlcpg

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const ClampWalletSyncStateHeightsForRollback = `-- name: ClampWalletSyncStateHeightsForRollback :execrows
UPDATE wallet_sync_states
SET
    synced_height = CASE
        WHEN
            synced_height IS NOT NULL
            AND synced_height >= $1
            THEN $2
        ELSE synced_height
    END,
    birthday_height = CASE
        WHEN
            birthday_height IS NOT NULL
            AND birthday_height >= $1
            THEN $2
        ELSE birthday_height
    END,
    updated_at = current_timestamp
WHERE
    (
        synced_height IS NOT NULL
        AND synced_height >= $1
    )
    OR (
        birthday_height IS NOT NULL
        AND birthday_height >= $1
    )
`

type ClampWalletSyncStateHeightsForRollbackParams struct {
	RollbackHeight sql.NullInt32
	NewHeight      sql.NullInt32
}

// Rewrites wallet sync-state heights so they stop referencing blocks that are
// about to be deleted during RollbackToBlock.
//
// How:
//   - Updates wallet_sync_states directly without joining other tables.
//   - Rewrites both synced_height and birthday_height in one statement so the
//     subsequent block delete does not violate `ON DELETE RESTRICT`.
//
// Performance:
//   - Touches only wallet_sync_states rows whose heights are at or above the
//     rollback boundary.
func (q *Queries) ClampWalletSyncStateHeightsForRollback(ctx context.Context, arg ClampWalletSyncStateHeightsForRollbackParams) (int64, error) {
	result, err := q.exec(ctx, q.clampWalletSyncStateHeightsForRollbackStmt, ClampWalletSyncStateHeightsForRollback, arg.RollbackHeight, arg.NewHeight)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DeleteBlocksAtOrAboveHeight = `-- name: DeleteBlocksAtOrAboveHeight :execrows
DELETE FROM blocks
WHERE block_height >= $1
`

// Deletes blocks at and after the provided height.
//
// How:
//   - Deletes directly from blocks by the natural height key.
//   - Relies on FK/trigger side effects to null transaction block references and
//     orphan coinbase rows.
//
// Performance:
// - Executes as a range delete over the block-height primary key.
func (q *Queries) DeleteBlocksAtOrAboveHeight(ctx context.Context, blockHeight int32) (int64, error) {
	result, err := q.exec(ctx, q.deleteBlocksAtOrAboveHeightStmt, DeleteBlocksAtOrAboveHeight, blockHeight)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DeleteUnminedTransactionByHash = `-- name: DeleteUnminedTransactionByHash :execrows
DELETE FROM transactions
WHERE
    wallet_id = $1
    AND tx_hash = $2
    AND block_height IS NULL
    AND status IN ('pending', 'published')
`

type DeleteUnminedTransactionByHashParams struct {
	WalletID int64
	TxHash   []byte
}

// Deletes an unconfirmed transaction row.
//
// How:
//   - Deletes only rows whose `block_height` is still NULL and whose status is
//     still in a live unconfirmed state (`pending` or `published`).
//   - Preserves orphaned/replaced/failed history; those rows must remain visible
//     for audit/reorg handling instead of being treated as ordinary mempool data.
//   - The caller must delete or restore dependent UTXO rows first.
//
// Performance:
// - Targets at most one row by `(wallet_id, tx_hash)`.
func (q *Queries) DeleteUnminedTransactionByHash(ctx context.Context, arg DeleteUnminedTransactionByHashParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteUnminedTransactionByHashStmt, DeleteUnminedTransactionByHash, arg.WalletID, arg.TxHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const GetTransactionByHash = `-- name: GetTransactionByHash :one
SELECT
    t.id,
    t.tx_hash,
    t.raw_tx,
    t.received_time,
    t.block_height,
    b.header_hash AS block_hash,
    b.block_timestamp,
    t.is_coinbase,
    t.status,
    t.label
FROM transactions AS t
LEFT JOIN blocks AS b ON t.block_height = b.block_height
WHERE t.wallet_id = $1 AND t.tx_hash = $2
`

type GetTransactionByHashParams struct {
	WalletID int64
	TxHash   []byte
}

type GetTransactionByHashRow struct {
	ID             int64
	TxHash         []byte
	RawTx          []byte
	ReceivedTime   time.Time
	BlockHeight    sql.NullInt32
	BlockHash      []byte
	BlockTimestamp sql.NullInt64
	IsCoinbase     bool
	Status         string
	Label          string
}

// Retrieves the full transaction row along with optional block metadata.
//
// How:
//   - Looks up the transaction by `(wallet_id, tx_hash)`.
//   - LEFT JOINs blocks on `block_height` so the same query handles mined and
//     unmined rows.
//
// Performance:
//   - The unique transaction lookup limits the join fanout to at most one block
//     row.
func (q *Queries) GetTransactionByHash(ctx context.Context, arg GetTransactionByHashParams) (GetTransactionByHashRow, error) {
	row := q.queryRow(ctx, q.getTransactionByHashStmt, GetTransactionByHash, arg.WalletID, arg.TxHash)
	var i GetTransactionByHashRow
	err := row.Scan(
		&i.ID,
		&i.TxHash,
		&i.RawTx,
		&i.ReceivedTime,
		&i.BlockHeight,
		&i.BlockHash,
		&i.BlockTimestamp,
		&i.IsCoinbase,
		&i.Status,
		&i.Label,
	)
	return i, err
}

const GetTransactionMetaByHash = `-- name: GetTransactionMetaByHash :one
SELECT
    id,
    block_height,
    is_coinbase,
    status,
    label
FROM transactions
WHERE wallet_id = $1 AND tx_hash = $2
`

type GetTransactionMetaByHashParams struct {
	WalletID int64
	TxHash   []byte
}

type GetTransactionMetaByHashRow struct {
	ID          int64
	BlockHeight sql.NullInt32
	IsCoinbase  bool
	Status      string
	Label       string
}

// Retrieves the primary key and lightweight transaction metadata.
//
// How:
//   - Reads only the transactions table because callers only need row identity
//     plus lightweight status/label fields.
//
// Performance:
// - Uses the wallet-scoped unique `(wallet_id, tx_hash)` lookup path.
func (q *Queries) GetTransactionMetaByHash(ctx context.Context, arg GetTransactionMetaByHashParams) (GetTransactionMetaByHashRow, error) {
	row := q.queryRow(ctx, q.getTransactionMetaByHashStmt, GetTransactionMetaByHash, arg.WalletID, arg.TxHash)
	var i GetTransactionMetaByHashRow
	err := row.Scan(
		&i.ID,
		&i.BlockHeight,
		&i.IsCoinbase,
		&i.Status,
		&i.Label,
	)
	return i, err
}

const InsertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    wallet_id,
    tx_hash,
    raw_tx,
    block_height,
    status,
    received_time,
    is_coinbase,
    label
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id
`

type InsertTransactionParams struct {
	WalletID     int64
	TxHash       []byte
	RawTx        []byte
	BlockHeight  sql.NullInt32
	Status       string
	ReceivedTime time.Time
	IsCoinbase   bool
	Label        string
}

// Inserts a wallet-scoped transaction row and returns its database ID.
//
// How:
//   - Writes only the transactions table.
//   - Expects the caller to have already resolved wallet scope and any optional
//     block reference.
//   - Expects the caller to supply the initial status explicitly so unmined rows
//     do not have to guess between `pending` and `published`.
//
// Performance:
//   - Single-row insert. The cost is dominated by the wallet/hash uniqueness
//     checks and any optional block foreign-key validation.
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error) {
	row := q.queryRow(ctx, q.insertTransactionStmt, InsertTransaction,
		arg.WalletID,
		arg.TxHash,
		arg.RawTx,
		arg.BlockHeight,
		arg.Status,
		arg.ReceivedTime,
		arg.IsCoinbase,
		arg.Label,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ListTransactionsByHeightRange = `-- name: ListTransactionsByHeightRange :many
SELECT
    t.id,
    t.tx_hash,
    t.raw_tx,
    t.received_time,
    t.block_height,
    b.header_hash AS block_hash,
    b.block_timestamp,
    t.is_coinbase,
    t.status,
    t.label
FROM transactions AS t
INNER JOIN blocks AS b ON t.block_height = b.block_height
WHERE
    t.wallet_id = $1
    AND t.block_height BETWEEN
    $2 AND $3
ORDER BY t.block_height, t.id
`

type ListTransactionsByHeightRangeParams struct {
	WalletID    int64
	StartHeight sql.NullInt32
	EndHeight   sql.NullInt32
}

type ListTransactionsByHeightRangeRow struct {
	ID             int64
	TxHash         []byte
	RawTx          []byte
	ReceivedTime   time.Time
	BlockHeight    sql.NullInt32
	BlockHash      []byte
	BlockTimestamp int64
	IsCoinbase     bool
	Status         string
	Label          string
}

// Lists all confirmed transactions for a wallet in the provided height range.
//
// How:
//   - Reads transactions in a wallet-scoped block-height range.
//   - INNER JOINs blocks on the natural `block_height` key to hydrate block hash
//     and timestamp for confirmed rows.
//
// Performance:
//   - The `(wallet_id, block_height)` index bounds the scan before the single-row
//     block join.
func (q *Queries) ListTransactionsByHeightRange(ctx context.Context, arg ListTransactionsByHeightRangeParams) ([]ListTransactionsByHeightRangeRow, error) {
	rows, err := q.query(ctx, q.listTransactionsByHeightRangeStmt, ListTransactionsByHeightRange, arg.WalletID, arg.StartHeight, arg.EndHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByHeightRangeRow
	for rows.Next() {
		var i ListTransactionsByHeightRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.RawTx,
			&i.ReceivedTime,
			&i.BlockHeight,
			&i.BlockHash,
			&i.BlockTimestamp,
			&i.IsCoinbase,
			&i.Status,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnminedTransactions = `-- name: ListUnminedTransactions :many
SELECT
    t.id,
    t.tx_hash,
    t.raw_tx,
    t.received_time,
    t.block_height,
    NULL::BYTEA AS block_hash,
    NULL::BIGINT AS block_timestamp,
    t.is_coinbase,
    t.status,
    t.label
FROM transactions AS t
WHERE
    t.wallet_id = $1
    AND t.block_height IS NULL
    AND t.status IN ('pending', 'published')
ORDER BY t.received_time DESC, t.id DESC
`

type ListUnminedTransactionsRow struct {
	ID             int64
	TxHash         []byte
	RawTx          []byte
	ReceivedTime   time.Time
	BlockHeight    sql.NullInt32
	BlockHash      []byte
	BlockTimestamp sql.NullInt64
	IsCoinbase     bool
	Status         string
	Label          string
}

// Lists all unconfirmed transactions for a wallet.
//
// How:
//   - Reads from transactions only and filters on blockless rows that are still
//     in a live unconfirmed state (`pending` or `published`).
//   - Excludes orphaned/replaced/failed history so rollback-produced coinbase
//     rows do not reappear as mempool transactions.
//   - Returns NULL block metadata explicitly because live unmined rows have no
//     block.
//
// Performance:
//   - Matches the partial unconfirmed index and orders by received time for the
//     common "latest mempool activity" read path.
func (q *Queries) ListUnminedTransactions(ctx context.Context, walletID int64) ([]ListUnminedTransactionsRow, error) {
	rows, err := q.query(ctx, q.listUnminedTransactionsStmt, ListUnminedTransactions, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnminedTransactionsRow
	for rows.Next() {
		var i ListUnminedTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.RawTx,
			&i.ReceivedTime,
			&i.BlockHeight,
			&i.BlockHash,
			&i.BlockTimestamp,
			&i.IsCoinbase,
			&i.Status,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ReconfirmOrphanedCoinbaseByHash = `-- name: ReconfirmOrphanedCoinbaseByHash :execrows
UPDATE transactions
SET
    block_height = $1,
    status = 'published'
WHERE
    wallet_id = $2
    AND tx_hash = $3
    AND is_coinbase
    AND block_height IS NULL
    AND status = 'orphaned'
`

type ReconfirmOrphanedCoinbaseByHashParams struct {
	BlockHeight sql.NullInt32
	WalletID    int64
	TxHash      []byte
}

// Restores one orphaned coinbase transaction to the best chain.
//
// How:
//   - Updates `block_height` and `status` in the same statement so coinbase rows
//     never pass through an invalid unconfirmed state.
//   - Restricts the update to rows that are already orphaned coinbase
//     transactions within the requested wallet.
//
// Performance:
// - Targets at most one row through the wallet-scoped unique tx-hash lookup.
func (q *Queries) ReconfirmOrphanedCoinbaseByHash(ctx context.Context, arg ReconfirmOrphanedCoinbaseByHashParams) (int64, error) {
	result, err := q.exec(ctx, q.reconfirmOrphanedCoinbaseByHashStmt, ReconfirmOrphanedCoinbaseByHash, arg.BlockHeight, arg.WalletID, arg.TxHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdateTransactionLabelByHash = `-- name: UpdateTransactionLabelByHash :execrows
UPDATE transactions
SET label = $1
WHERE
    wallet_id = $2
    AND tx_hash = $3
`

type UpdateTransactionLabelByHashParams struct {
	Label    string
	WalletID int64
	TxHash   []byte
}

// Updates only the user-visible transaction label.
//
// How:
//   - Leaves block assignment and status untouched.
//   - Exists for user-facing metadata edits only; wallet-internal state
//     transitions use dedicated helper queries.
//
// Performance:
// - Updates at most one row through the wallet-scoped unique tx-hash lookup.
func (q *Queries) UpdateTransactionLabelByHash(ctx context.Context, arg UpdateTransactionLabelByHashParams) (int64, error) {
	result, err := q.exec(ctx, q.updateTransactionLabelByHashStmt, UpdateTransactionLabelByHash, arg.Label, arg.WalletID, arg.TxHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdateTransactionStatusByIDs = `-- name: UpdateTransactionStatusByIDs :execrows
UPDATE transactions
SET status = $1
WHERE
    wallet_id = $2
    AND id = any($3::BIGINT [])
`

type UpdateTransactionStatusByIDsParams struct {
	Status   string
	WalletID int64
	TxIds    []int64
}

// Updates the wallet-relative status for a set of transaction row IDs.
//
// How:
//   - Exists for wallet-internal replacement and invalidation flows after the
//     caller has already identified the affected rows.
//   - Leaves block assignment untouched; rollback/disconnect continues to use the
//     dedicated rewind helpers below.
//
// Performance:
// - Restricts by wallet scope first, then matches only the provided ID set.
func (q *Queries) UpdateTransactionStatusByIDs(ctx context.Context, arg UpdateTransactionStatusByIDsParams) (int64, error) {
	result, err := q.exec(ctx, q.updateTransactionStatusByIDsStmt, UpdateTransactionStatusByIDs, arg.Status, arg.WalletID, pq.Array(arg.TxIds))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
